export const MONGO_IP = process.env.MONGO_IP || "mongo";
export const MONGO_PORT = process.env.MONGO_PORT || 27017;
export const MONGO_USER = process.env.MONGO_USER;
export const MONGO_PASSWORD = process.env.MONGO_PASSWORD;
export const REDIS_HOST = process.env.REDIS_HOST || 'redis';
export const REDIS_PORT = process.env.REDIS_PORT || 6379;
export const REDIS_USERNAME = process.env.REDIS_USERNAME || 'root';
export const REDIS_PASSWORD = process.env.REDIS_PASSWORD || 'password';
export const REDIS_SESSION_SECRET = process.env.REDIS_SESSION_SECRET || 'secret';